import type { DashboardConfig, ThemeId } from "./config-types";

export const THEMES: { id: ThemeId; label: string }[] = [
  { id: "midnight-teal", label: "Midnight Teal" },
  { id: "charcoal", label: "Charcoal" },
  { id: "deep-ocean", label: "Deep Ocean" },
  { id: "warm-ember", label: "Warm Ember" },
  { id: "amoled-black", label: "AMOLED Black" },
  { id: "macos-dark", label: "macOS Dark" },
];

export const DEFAULT_CONFIG: DashboardConfig = {
  haUrl: "",
  haToken: "",
  refreshInterval: 30,
  calendarEntities: ["calendar.family"],
  calendarEntityConfigs: [
    { entityId: "calendar.family", prefix: "", color: "hsl(var(--foreground))" },
  ],
  calendarDayColor: "",
  calendarTimeColor: "",
  calendarForecastDays: 7,
  calendarDisplay: {
    showEventBody: false,
    showEndDate: false,
    hideAllDayText: false,
    hideClockIcon: false,
    showWeekNumber: false,
    firstDayOfWeek: 1,
    limitEvents: false,
    maxEvents: 20,
    fontSizeDay: 12,
    fontSizeTime: 10,
    fontSizeTitle: 14,
    fontSizeBody: 12,
  },
  temperatureEntities: [
    { entityId: "sensor.living_room_temperature", label: "Living Room", color: "hsl(174, 72%, 50%)" },
    { entityId: "sensor.bedroom_temperature", label: "Bedroom", color: "hsl(32, 95%, 55%)" },
    { entityId: "sensor.outside_temperature", label: "Outside", color: "hsl(258, 60%, 60%)" },
  ],
  electricityPriceEntity: "sensor.nordpool_kwh_se3_sek_3_10_025",
  electricityForecastEntity: "",
  electricitySurcharge: 0,
  blackout: { enabled: false, from: "23:00", to: "06:00" },
  widgetLayouts: {},
  widgetOrder: [],
  rowColumns: {},
  rowHeights: {},
  lockWidgetHeights: false,
  gridColumns: 4,
  configBackendUrl: "",
  photoWidget: { photos: [], intervalSeconds: 10, displayMode: "contain", transition: "fade" },
  personEntities: [],
  weatherConfig: {
    entityId: "weather.home",
    forecastDays: 5,
    showPrecipitation: true,
    showSunrise: true,
    showSunset: true,
  },
  theme: "midnight-teal",
  foodMenuConfig: {
    source: "calendar",
    calendarEntity: "",
    skolmatenEntity: "",
    days: 5,
    skipWeekends: false,
    displayMode: "compact",
    style: {
      dayColor: "",
      dateColor: "",
      mealColor: "",
      dayFontSize: 0,
      dateFontSize: 0,
      mealFontSize: 0,
      dayFont: "",
      mealFont: "",
    },
  },
  generalSensors: [],
  sensorGrids: [],
  rssFeeds: [],
  notificationConfig: { showHANotifications: true, alertRules: [] },
  vehicles: [],
  pollenConfig: { sensors: [], forecastDays: 4, showLabel: true, showForecast: true },
  globalFontSizes: { heading: 12, value: 18, body: 14, label: 10 },
  widgetFontSizes: {},
  widgetStyles: {},
  personCardFontSizes: {},
  globalFormat: { dateFormat: "yyyy-MM-dd", timeFormat: "24h" },
  enableChores: false,
  choreWidgetConfig: {
    enabled: false,
    label: "Chores",
    icon: "mdi:clipboard-check-outline",
    showScoreboard: true,
    showUpcoming: true,
    showFairness: true,
    showCompleted: true,
    showAllChores: false,
    maxVisible: 0,
  },
  choreReminderConfig: {
    enabled: false,
    weekdayHour: 16,
    weekendHour: 10,
    maxChoresInNotification: 3,
    streakReminderEnabled: false,
    streakReminderHour: 18,
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "Europe/Stockholm",
  },
};
